# Generated by Django 6.0.2 on 2026-02-19 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_task_created_at_task_stage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='interests',
            field=models.TextField(blank=True, help_text='e.g., Coding, Art, Space, Robotics'),
        ),
    ]
