# Generated by Django 6.0.2 on 2026-02-19 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_profile_interests'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='target_program',
            field=models.CharField(blank=True, help_text='e.g. Computer Science at Waterloo', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='interests',
            field=models.TextField(blank=True),
        ),
    ]
